urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from inventory.views import showLastInventory, updateInventory,recordOrder
from inventory.views import orderHistory, inventoryHistory,startingInventory, notes, addNote
from inventory.views import recordDelivery, reportList, report, dailyReport
from inventory.views import latestInventories, latestOrders, unfilledOrders
from inventory.views import csvTotal, csvDailyReport
from inventory.views import tokensCollected, tokensDelivered
from inventory.views import recordTokenDelivery, recordTokenCollection
from inventory.views import addLocationTokenNote, addBoothTokenNote
from inventory.views import locationTokenNote, boothTokenNote, addBoothTokenNote, addLocationTokenNote
from inventory.views import collectionReport, deliveryReport, reconciliationReport
from inventory.views import csvCollectionReport,csvDeliveryReport, csvReconciliationReport
from inventory.views import showDashboardInventory, showDashboardOrders, showDashboardNotes, showVendorDashboard
urlpatterns = patterns('',
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
    #dashboard URLs
    url(r'^dashboard/inventory', showDashboardInventory),
    url(r'^dashboard/orders', showDashboardOrders),
    url(r'^dashboard/notes', showDashboardNotes),
    #vandor dashboard
    url(r'^dashboard/vendors', showVendorDashboard),
    #regular old URLs
    url(r'^location/(?P<location_number>[^\.]+)$', showLastInventory),
    url(r'^update-inventory/(?P<location_number>[^\.]+)$', updateInventory),
    url(r'^order-history/(?P<location_number>[^\.]+)$', orderHistory),
    url(r'^inventory-history/(?P<location_number>[^\.]+)$', inventoryHistory),
    url(r'^starting-inventory/(?P<location_number>[^\.]+)$', startingInventory),
    url(r'^notes/(?P<location_number>[^\.]+)$', notes),
    url(r'^add-note/(?P<location_number>[^\.]+)$', addNote),
    url(r'^record-order/(?P<location_number>[^\.]+)$', recordOrder),
    url(r'^record-delivery/(?P<location_number>[^\.]+)/(?P<order_id>[^\.]+)/(?P<order_delivered>[^\.]+)$', recordDelivery),
    url(r'^report/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',dailyReport),
    url(r'^report/total', report),
    url(r'^report/latest-inventories', latestInventories),
    url(r'^report/latest-orders', latestOrders),
    url(r'^report/unfilled-orders', unfilledOrders),
    #url(r'^report/latest-notes', latestNotes),
    url(r'^csv/report/total', csvTotal),
    url(r'^csv/report/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',csvDailyReport),
    url(r'^token/booth/(?P<location_number>[^\.]+)$', tokensDelivered),
    url(r'^token/location/(?P<location_number>[^\.]+)$', tokensCollected),
    url(r'^token/record-delivery/(?P<location_number>[^\.]+)$', recordTokenDelivery),
    url(r'^token/record-collection/(?P<location_number>[^\.]+)$', recordTokenCollection),
    url(r'^token/note/location/(?P<location_number>[^\.]+)$',locationTokenNote),
    url(r'^token/note/booth/(?P<location_number>[^\.]+)$', boothTokenNote),
    url(r'^token/add-note/location/(?P<location_number>[^\.]+)$',addLocationTokenNote),
    url(r'^token/add-note/booth/(?P<location_number>[^\.]+)$', addBoothTokenNote),
    url(r'^token/report/collection', collectionReport),
    url(r'^token/report/delivery', deliveryReport),
    url(r'^token/report/reconciliation', reconciliationReport),
    url(r'^csv/token/report/collection', csvCollectionReport),
    url(r'^csv/token/report/delivery', csvDeliveryReport),
    url(r'^csv/token/report/reconciliation', csvReconciliationReport),
)

if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )


if settings.DEBUG:
    urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
    )

inventory/models.py
from django.db import models
from datetime import datetime
from django.forms import ModelForm
from django import forms
from django.forms.widgets import TextInput, Input
from django.contrib.auth.models import User


class Html5NumInput(Input):
    input_type = 'number'

class OrderAgeWarningTime(models.Model):
    time = models.IntegerField(default=45)

class InventoryAgeWarningTime(models.Model):
    time = models.IntegerField(default=45)

class Beverage(models.Model):
    name=models.CharField(max_length=255)
    tokenvalue=models.IntegerField(default=0)

    def __unicode__(self):
        return self.name

class Location(models.Model):
    name=models.CharField(max_length=255)
    beverages = models.ManyToManyField(Beverage, through='LocationStandard')
    location_number=models.CharField(max_length=255)
    organization=models.CharField(max_length=255)
    vendor=models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

class LocationStandard(models.Model):
    beverage=models.ForeignKey(Beverage)
    location=models.ForeignKey(Location) #elim this or m2m
    start_units=models.IntegerField()
    fill_to_standard=models.IntegerField(max_length=10)
    order_when_below=models.IntegerField(max_length=10)

class OrderGroup(models.Model):
    id = models.AutoField(primary_key=True)

    def __unicode__(self):
        return str(self.id)


class Order(models.Model):
    group=models.ForeignKey(OrderGroup)
    location=models.ForeignKey(Location) #elim this or m2m
    beverage=models.ForeignKey(Beverage)
    units_ordered=models.IntegerField(max_length=10, default=0)
    order_delivered=models.NullBooleanField(null=True)
    timestamp=models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User)

class OrderForm(ModelForm):
    units_ordered=forms.IntegerField(initial=0, widget=Html5NumInput)
    class Meta:
        model=Beverage
        fields=('name', 'id')

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['units_ordered'].label = ''
        self.fields['units_ordered'].widget.attrs = {'class':'number'}
        self.fields['name'].widget.attrs = {'class':'labelish'}
        self.fields['name'].widget.attrs['readonly'] = True
        self.fields['name'].label = ''

class InventoryGroup(models.Model):
    id = models.AutoField(primary_key=True)

    def __unicode__(self):
        return str(self.id)

class Inventory(models.Model):
    group=models.ForeignKey(InventoryGroup)
    location=models.ForeignKey(Location) #elim this or m2m
    beverage=models.ForeignKey(Beverage)
    units_reported=models.IntegerField(max_length=10, default=0)
    timestamp=models.DateTimeField(auto_now=True)
    user=models.ForeignKey(User)

class InventoryForm(ModelForm):
    units_reported=forms.IntegerField(required=True, initial=0, widget=Html5NumInput)
    class Meta:
        model=Beverage
        fields=('name', 'id')

    def __init__(self, *args, **kwargs):
        super(InventoryForm, self).__init__(*args, **kwargs)
        self.fields['units_reported'].label = ''
        self.fields['units_reported'].widget.attrs = {'class':'number'}
        self.fields['name'].widget.attrs = {'class':'labelish'}
        self.fields['name'].widget.attrs['readonly'] = True
        self.fields['name'].label = ''

class Note(models.Model):
    location=models.ForeignKey(Location)
    timestamp=models.DateTimeField(auto_now=True)
    content=models.TextField(max_length=50000)
    user=models.ForeignKey(User)

class NoteForm(ModelForm):
    class Meta:
        model=Note
        fields=('content',)

class Token(models.Model):
    value=models.IntegerField(default=0)

class TokenBooth(models.Model):
    name=models.CharField(max_length=255)
    location_number=models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

class TokenDelivery(models.Model):
    location=models.ForeignKey(TokenBooth)
    tokens=models.IntegerField(default=0)
    timestamp=models.DateTimeField(auto_now=True)
    fiscal_day=models.DateField(default=datetime.now)
    user=models.ForeignKey(User)


class TokenDeliveryForm(ModelForm):
    tokens=forms.IntegerField(initial=0, widget=Html5NumInput)
    class Meta:
        model=TokenDelivery
        fields=('tokens',)

class TokenCollection(models.Model):
    location=models.ForeignKey(Location)
    tokens=models.IntegerField(default=0)
    timestamp=models.DateTimeField(auto_now=True)
    fiscal_day=models.DateField(default=datetime.now)
    user=models.ForeignKey(User)

class TokenCollectionForm(ModelForm):
    tokens=forms.IntegerField(initial=0, widget=Html5NumInput)
    class Meta:
        model=TokenCollection
        fields=('tokens',)

class LocationTokenNote(models.Model):
    location=models.ForeignKey(Location)
    timestamp=models.DateTimeField(auto_now=True)
    content=models.TextField(max_length=50000)
    user=models.ForeignKey(User)

class LocationTokenNoteForm(ModelForm):
    class Meta:
        model=LocationTokenNote
        fields=('content',)

class BoothTokenNote(models.Model):
    location=models.ForeignKey(TokenBooth)
    timestamp=models.DateTimeField(auto_now=True)
    content=models.TextField(max_length=50000)
    user=models.ForeignKey(User)

class BoothTokenNoteForm(ModelForm):
    class Meta:
        model=BoothTokenNote
        fields=('content',)

templates/base.html
<!doctype html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block page_title %}Dublin Irish Festival{% endblock %}</title>
    <meta name="description" content="{% block meta_description %}{% endblock %}" />
    <meta name="author" content="{% block meta_author %}{% endblock %}" />
    <meta name="viewport" content="width=device-width,initial-scale=1 maximum-scale=1, user-scalable=0">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/jquery.jscrollpane.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css?v=2" />
    <script src="{{ STATIC_URL }}js/libs/modernizr-2.5.3.min.js"></script>
  </head>
  <body class="{% block body_class %}{% endblock %}" id="{% block body_id %} {% endblock %}">
	<div id="container">
	    <header>
		<div class="row">
		    <ul id="nav">
			<li class="last-inventory"><a href="/location/{{location.location_number}}">Last Reported Inventory</a></li>
			<li class="order-history"><a href="/order-history/{{location.location_number}}">Order History</a></li>
			<li class="inventory-history" ><a href="/inventory-history/{{location.location_number}}">Inventory History</a></li>
			<li class="starting-inventory"><a href="/starting-inventory/{{location.location_number}}">Starting Inventory</a></li>
			<li class="notes"><a href="/notes/{{location.location_number}}">Notes</a></li>
			<li class="dashboard"><a href="/dashboard/inventory">Dashboard</a></li>
      <li class="logout"><a href="/accounts/logout/">{{ user.first_name|first }}. {{ user.last_name}} | Logout</a></li>
		    </ul>		
		    {% block header %}
		    {% endblock %}
		</div>
	    </header>
	    <div id="main" role="main">
		<div class="row">
		{% block base_content%}Base{% endblock %}
		</div>
	    </div>
	    <footer>
		{% block footer %}
		{% endblock %}
	    </footer>
	</div> <!-- end of #container -->
	<div id="blanket"></div>
	<div id="modalOuter">
	    {% block modal_content%}
	    {% endblock %}
	</div>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/libs/jquery-1.7.1.min.js"><\/script>')</script>
      
      
	<!-- scripts concatenated and minified via ant build script-->
	<script defer src="{{ STATIC_URL }}js/plugins.js"></script>
	<script defer src="{{ STATIC_URL }}js/script-min.js"></script>
	<!-- end scripts-->
      
      
	<script>
	  //window._gaq = [['_setAccount','UA-28033583-1'],['_trackPageview'],['_trackPageLoadTime']];
	  //Modernizr.load({
	  //  load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
	  //});
	</script>
      
      
	<!--[if lt IE 7 ]>
	  <script src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
	  <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
	<![endif]-->
  </body>
</html>

templates/collection-report.html
{% extends "tokenreport-base.html" %}

{% block base_content %}

<a href="/csv/token/report/collection">Download as csv</a>

<table>
  <thead>
    <tr>
      <th>Beverage Station</th>
    {% for day in dates %}
    <th>{{ day|date:"l" }}</th>
    {% endfor %}
    <th>Total</th>
  </tr>
  </thead><tbody>
  {% for location, row in grid %}
  <tr>
    <td>{{ location.name }}</td>
    {% for total in row %}
    <td>{{ total }}</td>
    {% endfor %}
  </tr>
    {% endfor  %}
  </tbody>
  <tr>
    <td>Grand Total</td>
    {% for daytotal in grandtotal %}
    <td>
      {{ daytotal }}
    </td>
    {% endfor %}
  </tr>

</table>
{% endblock %}

templates/daily-report.html
{% extends "totals-base.html" %}
{% block base_content %}
{% block body_class %}{% endblock %}{% block body_id %}{% endblock %}
<h1></h1>
    <a href="/csv{{ request.path }}">download as csv</a>
    <table>
        <thead>
        </thead>
        <tbody>
          <tr>
            <th>Location#</th>
            <th>Location</th>
            {% for beverage in beverages %}
            <th>{{ beverage }}</th>
            {% endfor %}
          </tr>
         {% for location, row in grid %}
          <tr>
            <th>{{ location.location_number }}</th>
            <th>{{ location }}</th>
            {% for total in row %}
            <td>{{ total }}</td>
            {% endfor %}
          </tr>
         {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/index.html
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title></title>
  <meta name="description" content="">

  <meta name="viewport" content="width=device-width">
  <link rel="stylesheet" href="css/style.css">

  <script src="js/libs/modernizr-2.5.3.min.js"></script>
</head>
<body>
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
  <header>

  </header>
  <div role="main">

  </div>
  <footer>

  </footer>


  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.1.min.js"><\/script>')</script>

  <script src="js/plugins.js"></script>
  <script src="js/script.js"></script>

  <script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>
</body>
</html>

templates/latest-orders.html
{% extends "reports-base.html" %}
{% block body_class %}{% endblock %}{% block body_id %}latest-orders{% endblock %}

{% block base_content %}

{% for order in orders %}

<p>{{ order.location }} - {{ order.beverage }} {{ order.units_ordered }}- {{ order.order_delivered }}</p>
{% endfor %}


{% for location, beverage, time, reporter in grid %}

<h1>{{ location }} - {{ location.location_number }}</h1>
<p class="datetime"><b>Reported At: </b>{{time.0}}</p>
<p class="reporter"><b>Reported By: </b>{{reporter.0.first_name}} {{reporter.0.last_name}}</p>
<table>
  <thead>
    <tr>
      <th>Beverage Offered</th>
      <th>Units Ordered</th>
      <th>Order Delivered</th>
    </tr>
  </thead>
  <tbody>
    {% for thing in beverage %}
    {% if thing.1 > 0 %}
    <tr>
      <td>
        {{ thing.0 }}
      </td>
      <td>
        {{ thing.1 }}
      </td>
      <td>
        {{ thing.2 }}
      </td>
  </tr>
    {% endif %}
    {% endfor %}
  </tbody>
</table>
{% endfor %}
{% endblock %}

templates/latest-report.html
{% extends "reports-base.html" %}
{% block body_class %}{% endblock %}{% block body_id%}latest-inventories{% endblock %}

{% block base_content %}
{% for location, beverage, time, reporter in grid %}

<h1>{{ location }} - {{ location.location_number }}</h1>
<p class="datetime"><b>Reported At: </b>{{time.0}}</p>
<p class="reporter"><b>Reported By: </b>{{reporter.0.first_name}} {{reporter.0.last_name}}</p>
<table>
  <thead>
    <tr>
      <th>Beverage Offered</th>
      <th>Units Reported</th>
      <th>Order When Below</th>
      <th>Fill To Standard</th>
    </tr>
  </thead>
  <tbody>
    {% for thing in beverage %}
    <tr>
      <td>
        {{ thing.0 }}
      </td>
      <td class="{% if thing.1 <= thing.2 %}low{% endif %}">
        {{ thing.1 }}
      </td>
      <td>
        {{ thing.2 }}
      </td>
      <td>
        {{ thing.3 }}
    </td>
  </tr>
    {% endfor %}
  </tbody>
</table>
{% endfor %}
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load i18n %}
{% block page_title %}Login{% endblock %}
{% block body_class %}user-account{% endblock %}
{% block body_id %}login{% endblock %}
{% block base_content %}
    <div class="main-content">
        <form method="post" action=".">
        {% csrf_token %}
        {{ form.as_p }}
        
          <input type="submit" value="{% trans 'Log in' %}" />
          <input type="hidden" name="next" value="{{ next }}" />
        </form>

        <h2>{% trans "Forgot password" %}?</h2>
        <p><a href="{% url auth_password_reset %}" class="buttonish">{% trans "Reset it" %}!</a></p>
        <h2>{% trans "Not member" %}?</h2>
        <p><a href="{% url registration_register %}"class="buttonish">{% trans "Register" %}!</a></p>
    </div>
{% endblock %}

templates/order-history.html
{% extends "base.html" %}
{% block body_class %}{% endblock %}{% block body_id %}order-history{% endblock %}
{% block base_content %}

<h1>{{ location.name }} - {{ location.location_number }}</h1>
<h3 class="orgName">{{ location.organization }}</h3>

<div class="table-wrap">
    <table class="order-table">
	<thead>
	    <tr>
		<th>Beverage Offered</th>
		<th>Units Ordered</th>
		<th>Order Sent</th>
	    </tr>
	</thead>
	
	{% for o in order %}
  {% if o.units_ordered != 0 %}
	{% ifchanged %}
  <tr class="datetime">
    <td colspan="4"><b>Reported At:</b> {{o.timestamp|date:"fA l F j, Y" }}</td>
  </tr>
  <tr class="reporter">
    <td colspan="4"><b>Reported By:</b> {{ o.user.first_name}} {{ o.user.last_name}}</td>
  </tr>
	{% endifchanged %}
  <tr data-group="{{ o.group }}" {% if o.beverage.name == 'Ice' %} class="ice"{% endif %}>
    <td >{{ o.beverage.name }}</td>
      <td>{{ o.units_ordered }}</td>
      {% if perms.inventory.add_order %}
      {% if o.order_delivered == False %}
        <td></td>
        {% else%}
        <td class="deliver" data-deliver="/record-delivery/{{location.location_number}}/{{o.pk}}/{{o.order_delivered}}">{{o.order_delivered}}</td>
        {% endif %}
      {% else %}
      <td>{{ o.order_delivered }}</td>
      {% endif %}
	</tr>
  {% endif %}
	{% endfor %}
    </table>
</div>

{%if perms.inventory.add_inventory %}
<a class="buttonish" href="/update-inventory/{{location.location_number}}">Update Inventory</a>
{% endif %}
{% if perms.inventory.add_order %}
<a class="buttonish" href="/record-order/{{location.location_number}}">Record Order</a>
{% endif %}

{% endblock %}

templates/record-delivery.html
{% extends "token-base.html" %}
{% block base_content%}
<h1>{{ location }}</h1>
<h2>Record Token Delivery</h2>
<form action="/token/record-delivery/{{ location.location_number }}" method="post">
  {% csrf_token %}
  {{ form.as_p }}

<input type="submit" class="submit" value="Submit Tokens Delivered"/>
<a class="cancelButtonish" href="/token/booth/{{location.location_number}}">Cancel</a>
</form>
{% endblock %}

templates/reportList.html
{% extends "reports-base.html" %}
{% block base_content %}
{% block body_class %}{% endblock %}{% block body_id %}{% endblock %}

{% for order in orders %}
{% ifchanged %}
<a
  href="/report/{{order.timestamp|date:"Y"}}/{{order.timestamp|date:"m"}}/{{order.timestamp|date:"d"}}">{{ order.timestamp|date:"l" }}</a>
{% endifchanged %}
{% endfor %}

<h3>Festival Total</h3>
<a href="/report/total">Click here</a>
{% endblock %}

templates/token-base.html
<!doctype html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block page_title %}Dublin Irish Festival{% endblock %}</title>
    <meta name="description" content="{% block meta_description %}{% endblock %}" />
    <meta name="author" content="{% block meta_author %}{% endblock %}" />
    <meta name="viewport" content="width=device-width,initial-scale=1 maximum-scale=1, user-scalable=0">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css?v=2" />
    <script src="{{ STATIC_URL }}js/libs/modernizr-2.5.3.min.js"></script>
  </head>
  <body class="{% block body_class %}{% endblock %}" id="{% block body_id %} {% endblock %}">
	<div id="container">
	    <header>
		<div class="row">
      <ul id="nav">
      {% if locationtype == "booth" %}
        <li class="tokens-delivered"><a href="/token/booth/{{location.location_number}}">Tokens Delivered</a></li>
        <li class="booth-notes"><a href="/token/note/booth/{{location.location_number}}">Notes</a></li>
      {% else %}
        <li class="tokens-delivered"><a href="/token/location/{{location.location_number}}">Tokens Collected</a></li>
        <li class="location-notes"><a href="/token/note/location/{{location.location_number}}">Notes</a></li>
      {% endif %}
      <li class="logout"><a href="/accounts/logout/">{{ user.first_name|first }}. {{ user.last_name}} | Logout</a></li>
      </ul>		
		    {% block header %}
		    {% endblock %}
		</div>
	    </header>
	    <div id="main" role="main">
		<div class="row">
		{% block base_content%}Base{% endblock %}
		</div>
	    </div>
	    <footer>
		{% block footer %}
		{% endblock %}
	    </footer>
	</div> <!-- end of #container -->
	<div id="blanket"></div>
	<div id="modalOuter">
	    {% block modal_content%}
	    {% endblock %}
	</div>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/libs/jquery-1.7.1.min.js"><\/script>')</script>
      
      
	<!-- scripts concatenated and minified via ant build script-->
	<script defer src="{{ STATIC_URL }}js/plugins.js"></script>
	<script defer src="{{ STATIC_URL }}js/script.js"></script>
	<!-- end scripts-->
      
      
	<script>
	  //window._gaq = [['_setAccount','UA-28033583-1'],['_trackPageview'],['_trackPageLoadTime']];
	  //Modernizr.load({
	  //  load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
	  //});
	</script>
      
      
	<!--[if lt IE 7 ]>
	  <script src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
	  <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
	<![endif]-->
  </body>
</html>

templates/tokens-collected.html
{% extends "token-base.html" %}

{% block base_content %}
<h2>{{ location }} - {{ location.location_number }}</h2>
<h3 class="orgName">{{ location.organization }}</h3>

<div class="table-wrap">
  <table>
	  <thead>
	    <tr>
        <th>Tokens Collected</th>
        <th>Date/Time Collected</th>
        <th>Reporter</th>
	    </tr>
    </thead>
{% for token in tokens %}
<tr>
  <td>{{ token.tokens }}</td>
  <td>{{ token.timestamp }}</td>
  <td>{{ token.user.first_name }} {{ token.user.last_name }}</td>
</tr>

{% endfor %}
</table>
</div>
<button><a href="/token/record-collection/{{ location.location_number }}">Record Token Collection </a></button>

{% endblock %}